### ISSUE TITLE
Potential problems

### ISSUE THREAD

**Issue by ozxybox** [Trico-Everfire/SteamAppPathProvider#2]
- [x] This code is constantly performing a look up for the same pair at key 'libraryfolders'. I would suggest getting `libFolder["libraryfolders"]` *once* and storing it as a `KeyValue&` before entering the loop
https://github.com/Trico-Everfire/SteamAppPathProvider/blob/396c4f72581f31e959156656a8ca9597a8da3c9c/FilesystemSearchProvider.h#L249
https://github.com/Trico-Everfire/SteamAppPathProvider/blob/396c4f72581f31e959156656a8ca9597a8da3c9c/FilesystemSearchProvider.h#L251

- [x] This sounds like it should be handled as an error, rather than sending in the whole kv.
https://github.com/Trico-Everfire/SteamAppPathProvider/blob/396c4f72581f31e959156656a8ca9597a8da3c9c/FilesystemSearchProvider.h#L262

- [x] The lengths of these strings are already known from the earlier parse.
https://github.com/Trico-Everfire/SteamAppPathProvider/blob/396c4f72581f31e959156656a8ca9597a8da3c9c/FilesystemSearchProvider.h#L269
https://github.com/Trico-Everfire/SteamAppPathProvider/blob/396c4f72581f31e959156656a8ca9597a8da3c9c/FilesystemSearchProvider.h#L270

- [x] The aforementioned string lengths can be accessed by changing this vector to hold type `kvString_t`.
https://github.com/Trico-Everfire/SteamAppPathProvider/blob/396c4f72581f31e959156656a8ca9597a8da3c9c/FilesystemSearchProvider.h#L245

- [x] The length passed to this should be `MAX_PATH`, not folder's string length.
https://github.com/Trico-Everfire/SteamAppPathProvider/blob/396c4f72581f31e959156656a8ca9597a8da3c9c/FilesystemSearchProvider.h#L286
https://github.com/Trico-Everfire/SteamAppPathProvider/blob/396c4f72581f31e959156656a8ca9597a8da3c9c/FilesystemSearchProvider.h#L287

- [x] Is this a memory leak? I don't see a call to delete this memory.
https://github.com/Trico-Everfire/SteamAppPathProvider/blob/396c4f72581f31e959156656a8ca9597a8da3c9c/FilesystemSearchProvider.h#L309

**Comment by Trico-Everfire** [comment]
> This sounds like it should be handled as an error, rather than sending in the whole kv.

Well, I had a hard time deciphering what was asked of me when I removed Source's KeyValues. according to my backtracing, it just shoved the whole key value in there. I am probably fucking up here. but I don't know what else to do. Not to mention, that code is on the condition someone is on the old libraryfolders structure, which is very slim in the first place. I don't even remember the old format, let alone how to account for it.

**Comment by ozxybox** [comment]
There's not a really great way to fire off an error in here. You could throw an exception, fire an assert, add in error codes, or just use a continue. Passing in the whole kv is most likely to just cause you future problems down the line :P

**Comment by Trico-Everfire** [comment]
>  Is this a memory leak? I don't see a call to delete this memory.

Nope! This is what's being stored in the Game struct for the games vector. 
libFolders falls out of scope, these char arrays are deleted by:
https://github.com/Trico-Everfire/SteamAppPathProvider/blob/396c4f72581f31e959156656a8ca9597a8da3c9c/FilesystemSearchProvider.h#L430

**Comment by Trico-Everfire** [comment]
Confirm all issues have been resolved and new ones haven't arrived.

**Comment by ozxybox** [comment]
- [x] I would suggest against modifying the result of a call to `KeyValue::Value`, you're more likely to do yourself harm than good.
https://github.com/Trico-Everfire/SteamAppPathProvider/blob/8b2710a9db37b5362bc79ff3e6e98eb20ebcdd4f/FilesystemSearchProvider.h#L279

- [x] This could lead to a potential overrun later if this string is not null terminated.
https://github.com/Trico-Everfire/SteamAppPathProvider/blob/8b2710a9db37b5362bc79ff3e6e98eb20ebcdd4f/FilesystemSearchProvider.h#L311

- [x] You may want to use a strncpy here for safety fun.
https://github.com/Trico-Everfire/SteamAppPathProvider/blob/8b2710a9db37b5362bc79ff3e6e98eb20ebcdd4f/FilesystemSearchProvider.h#L406

- [x] The call to `std::remove` is just calling the deconstructor on `Game`, not freeing `library`. I would suggest iterating over `games` and freeing the strings rather than adding a deconstructor though--just easier. 
https://github.com/Trico-Everfire/SteamAppPathProvider/blob/8b2710a9db37b5362bc79ff3e6e98eb20ebcdd4f/FilesystemSearchProvider.h#L444

- [x] If you implement string literal versions of these macros, you can use string literal concatenation to remove some extra unnecessary calls to `S_HAppendSlash`. 
https://github.com/Trico-Everfire/SteamAppPathProvider/blob/8b2710a9db37b5362bc79ff3e6e98eb20ebcdd4f/FilesystemSearchProvider.h#L33

**Comment by Trico-Everfire** [comment]
> I would suggest against modifying the result of a call to KeyValue::Value, you're more likely to do yourself harm than good.

So... just memcpy?

**Comment by ozxybox** [comment]
Sure, memcpy to a buf, strncpy, snprintf, etc. nothing specific required, just dont modify that data. I should probably ensure that string is const.
Post solidify, that memory is all lined up in one huge array, so you're overwriting another string (which is the only reason it's not outright crashing).

**Comment by Trico-Everfire** [comment]
> This could lead to a potential overrun later if this string is not null terminated.

What do you mean? is pathString not null terminated?

**Comment by Trico-Everfire** [comment]
> If you implement string literal versions of these macros, you can use string literal concatenation to remove some extra unnecessary calls to S_HAppendSlash.

What do you mean by this? how do I?

**Comment by ozxybox** [comment]
> > This could lead to a potential overrun later if this string is not null terminated.
> 
> What do you mean? is pathString not null terminated?

When you `memcpy` a string into a buffer, and the string is longer than the buffer, the string is truncated but not null terminated. 

This is why there's `strncpy`, but it's a bit of a flawed function itself, as it fills the whole array past the string with zeros. People will often use `snprintf` or implement their own (like `strlcpy`) to do what `strncpy` should do.

Or, save yourself some effort and just null terminate it after the `memcpy`.

**Comment by ozxybox** [comment]
> > If you implement string literal versions of these macros, you can use string literal concatenation to remove some extra unnecessary calls to S_HAppendSlash.
> 
> What do you mean by this? how do I?

If you put strings next to each other like
```cpp
"Hello" "_" "World"
```
the compiler will resolve it out like this into one string
```cpp
"Hello_World"
```
You can use this to save yourself on a few extra function calls and move some operations to be done at compile time

**Comment by Trico-Everfire** [comment]
Seen as resolved.
